#!/bin/bash

while read -r line; do
    [[ $line != *open* ]] && continue
    echo  $line | awk '{ printf "%s: ",$2 }'  
    echo $line |
        sed 's/, /\n/g; s/Ports: /\n/g' | 
        grep --color=never open | 
        cut -d'/' -f1 | 
        tr '\n' ',' |
        sed -r 's/,$/\n/g'
done

