#!/bin/bash

DEBUG=false

debug_log(){
    $DEBUG && echo "$*" >> /tmp/out.log
}

arg=${1/\~/$HOME}
pid_of_shell=$(ps --ppid=$PPID | grep -i "pts" | awk '{ print $1 }')
cwd_of_shell=$(readlink /proc/$pid_of_shell/cwd)

debug_log "$pid_of_shell --> $cwd_of_shell"
debug_log $(ps --ppid=$PPID)
cd "$cwd_of_shell"

debug_log "arg: $arg"
if [[ $arg =~ ":" ]]; then
    filename="${arg/:*/}"
    linenumber="${arg/*:/}"
    debug_log gvim "+$linenumber" "$filename"
    gvim "+$linenumber" "$filename"
else
    debu_log gvim "$arg"
    gvim "$arg"
fi
