#!/bin/sh
pid_of_shell=$(ps --ppid=$PPID | grep -i "pts" | awk '{ print $1 }')
cwd_of_shell=$(readlink /proc/$pid_of_shell/cwd)
#echo "$pid_of_shell --> $cwd_of_shell" >> /tmp/out.log
#ps --ppid=$PPID >> /tmp/out.log

cd "$cwd_of_shell"

arg="$1"
if [[ $arg =~ ":" ]]; then
    filename=$(echo "$arg" | cut -d':' -f1)
    linenumber=$(echo "$arg" | cut -d':' -f2)
    gvim -c "cd $PWD" +$linenumber $filename
else
    gvim -c "cd $PWD" "$arg"
fi
